### ISSUE TITLE
关于[yolo]层数

### ISSUE THREAD

**Issue by walink** [BruceDone/darknet_demo#3]
train.cfg  中filters=(class+5)*3    这里面的3是有三层yolo层的意思吗？

为什么train.cfg只有两层【yolo】函数 ，这个会有影响吗，多谢指点

**Comment by walink** [comment]
tiny网络确实只有两层yolo输出。

**Comment by BruceDone** [comment]
嗯，对的，这次使用的是tiny网络，正常的网络层数会更多一点
